name: setup Vulkan action
description: download and unpack Vulkan for gh actions
    
runs:
  using: composite
  steps:
    - name: setup 7-Zip
      uses: milliewalky/setup-7-zip@v2

    - name: download Vulkan
      shell: cmd
      working-directory: ${{ runner.temp }}
      run: curl -L -o vulkan_sdk.exe https://sdk.lunarg.com/sdk/download/1.3.275.0/windows/VulkanSDK-1.3.275.0-Installer.exe

    - name: install Vulkan
      shell: cmd
      working-directory: ${{ runner.temp }}
      run: 7z x vulkan_sdk.exe -aoa -o%cd%\VulkanSDK\1.3.275.0

    - name: add `VULKAN_SDK` env variable to path
      shell: cmd
      run: |
        echo VULKAN_SDK=${{ runner.temp }}\VulkanSDK\1.3.275.0>>%GITHUB_ENV%

    - name: add `VULKAN_SDK\Bin` to path
      shell: cmd
      run: |
        echo %VULKAN_SDK%\Bin>>%GITHUB_PATH%
